server:
  port: 8080
spring:
  application:
    name: "ms_cinema"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  postgres:
    database: "cinema"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "admin"
    schema: "schcined"
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
