server:
  port: 8080
spring:
  application:
    name: "ms_cinema"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: local

adapters:
  postgres:
    database: "cinema"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "admin"
    schema: "schcined"

helpers:
  secrets-manager:
    endpoint: http://localhost:4566
    cacheSize: 5
    cacheTime: 3600
    postgres: cinema-local-secretrds-CNX


management:
  endpoints:
    web:
      exposure:
        include: "health"

  endpoint:
    health:
      probes:
        enabled: true


cors:
  allowed-origins: "http://localhost:4200, http://localhost:8080"