server:
  port: 8080
spring:
  application:
    name: "ms_cinema"
  devtools:
    add-properties: false
  profiles:
    include: "local"
  logging:
    level:
      root: "INFO"
      reactor:
        netty: false
adapters:
  postgres:
    database: "cinema"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "admin"
    schema: "schcined"
    pool:
      initial-size: 12
      max-size: 15
      max-idle-time: 10

helpers:
  secrets-manager:
    endpoint: http://localhost:4566
    cache-size: 5
    cache-time: 3600
    postgres: cinema-local-secretrds-CNX